{{- if .Values.externalSecrets.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: gitblog-secret
  namespace: gitblog

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: gitblog-secret

  data:
    - secretKey: DB_USER
      remoteRef:
        key: gitblog-secrets
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: gitblog-secrets
        property: DB_PASSWORD

    - secretKey: JWT_SECRET
      remoteRef:
        key: gitblog-secrets
        property: JWT_SECRET

{{- end }}