apiVersion: v1
kind: Secret

metadata:
  name: gitblog-secret
  annotations:
    # Tell Helm this is a pre-install requirement
    "helm.sh/hook": pre-install,pre-upgrade
    # A weight of "-2" ensures it creates BEFORE the job (which is "-1")
    "helm.sh/hook-weight": "-2"
    # Keep it in the cluster after a successful run so the app can use it
    "helm.sh/hook-delete-policy": before-hook-creation

type: Opaque

stringData:
  DB_USER: {{ .Values.secret.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}