apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: gitblog
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/rohanan07/Gitblog-Gitops-Repo.git

    targetRevision: HEAD

    path: helm/gitblog

  destination:
    server: https://kubernetes.default.svc

    namespace: gitblog

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true