frontend:
  replicaCount: 2

  image:
    repository: 585539844585.dkr.ecr.ap-south-1.amazonaws.com/gitblog-frontend
    tag: "2.0"

  service:
    port: 80

backend:
  replicaCount: 2

  image:
    repository: 585539844585.dkr.ecr.ap-south-1.amazonaws.com/gitblog-backend
    tag: "4.0"

  service:
    port: 5000

config:
  DB_HOST: gitblog-dev.cfwa8iu8yfep.ap-south-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: gitblog

secret:
  DB_USER: postgres
  DB_PASSWORD: 'pass'
  JWT_SECRET: super-secret-jwt-key

ingress:
  enabled: true